import { auth } from './firebase.js';
import { onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/10.7.1/firebase-auth.js';

const programs={neet:[
{id:'neet-velocity',level:'Class 11 • 2 Years',name:'Velocity NEET',copy:'Build strong NCERT concepts from Class 11 with a complete two-year preparation rhythm.',meta:['Complete syllabus','Weekly tests','Personal mentoring'],page:'velocity_neet.html'},
{id:'neet-momentum',level:'Class 12 • 1 Year',name:'Momentum NEET',copy:'Balance boards and NEET through focused coverage, testing, and strategic revision.',meta:['Board + NEET plan','Performance tracking','Doubt support'],page:'momentum_neet.html'},
{id:'neet-power',level:'12th Passed • 1 Year',name:'Power NEET',copy:'A rigorous dropper program designed for complete syllabus mastery and score improvement.',meta:['Intensive practice','Full-length mocks','Targeted correction'],page:'power_neet.html'},
{id:'neet-impulse',level:'Crash Course • 3 Months',name:'Impulse NEET',copy:'Fast, structured revision for the final preparation phase with NCERT-first practice.',meta:['Rapid revision','Exam strategy','Mock-test sprint'],page:'impulse_neet.html'}],jee:[
{id:'jee-velocity',level:'Class 11 • 2 Years',name:'Velocity JEE',copy:'Develop deep concepts and advanced problem-solving skills from the foundation year.',meta:['Main + Advanced','Progressive practice','Personal mentoring'],page:'Velocity_jee.html'},
{id:'jee-momentum',level:'Class 12 • 1 Year',name:'Momentum JEE',copy:'A focused final-year program aligning board preparation with JEE Main and Advanced.',meta:['Full coverage','Advanced problems','Weekly analysis'],page:'momentum_jee.html'},
{id:'jee-power',level:'12th Passed • 1 Year',name:'Power JEE',copy:'An intensive dropper program for students committed to a major rank improvement.',meta:['High-level practice','Rigorous tests','Strategic revision'],page:'power_jee.html'},
{id:'jee-impulse',level:'Crash Course • 3 Months',name:'Impulse JEE',copy:'A concentrated final sprint covering revision, testing, and exam-day execution.',meta:['Revision plan','Mock-test series','Speed + accuracy'],page:'impulse_jee.html'}]};
const grid=document.querySelector('#programGrid');let active='neet';
function render(){grid.innerHTML=programs[active].map(p=>`<article class="program-card"><span class="program-level">${p.level}</span><h3>${p.name}</h3><p>${p.copy}</p><div class="program-meta">${p.meta.map(x=>`<span>${x}</span>`).join('')}</div><div class="program-actions"><a href="${p.page}">Details</a><a href="buy_course.html?course=${p.id}">Enroll</a></div></article>`).join('');}
document.querySelectorAll('.program-switch button').forEach(button=>button.addEventListener('click',()=>{active=button.dataset.track;document.querySelectorAll('.program-switch button').forEach(b=>b.classList.toggle('active',b===button));render();}));render();
const menu=document.querySelector('.menu-button'),nav=document.querySelector('.nav-links');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.textContent=open?'×':'☰';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation');document.body.style.overflow=open?'hidden':'';});nav.addEventListener('click',event=>{if(event.target.closest('a')){nav.classList.remove('open');menu.textContent='☰';menu.setAttribute('aria-expanded','false');document.body.style.overflow='';}});document.querySelector('#year').textContent=new Date().getFullYear();
document.querySelector('.logout').addEventListener('click',async()=>{await signOut(auth);location.href='index.html';});onAuthStateChanged(auth,user=>{document.querySelectorAll('.auth-guest').forEach(el=>el.hidden=!!user);document.querySelectorAll('.auth-user').forEach(el=>el.hidden=!user);});
